---
title: "JD Website"
author: "Jorge David Morales"
date: "`r Sys.Date()`"
#output: 
#  html_document:
#    theme: simplex
#    toc: true
#    toc_depth: 2
#    toc_float: true
---

# COVID-19

```{r, include=FALSE, message=FALSE, warning=FALSE}
# Enviroment
library(tidyverse)
library(directlabels)
library(knitr)
library(kableExtra)
```

Información tomada del GitHub de la Universidad Johns Hopkins, US:   
https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data  

```{r, include=FALSE}
# Johns Hopkins Dataset
covid19.jh.c <- read.csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv",
                       header = T, sep = ",", stringsAsFactors = F)

covid19.jh.r <- read.csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv",
                       header = T, sep = ",", stringsAsFactors = F)

covid19.jh.d <- read.csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv",
                       header = T, sep = ",", stringsAsFactors = F)
```

```{r, include=FALSE}
# Data Analysis

# Confirmed
covid19.jh.c <- covid19.jh.c %>% 
  select(-c(Province.State, Lat, Long)) %>% 
  gather(key = "Report.Date", value = "Confirmed.p", -Country.Region) %>% 
  mutate(Report.Date = as.Date(str_remove(Report.Date, "X"), '%m.%d.%y'),
         Country.Region = ifelse(Country.Region=='United Kingdom','UK',Country.Region)) %>% 
  group_by(Country.Region, Report.Date) %>% 
  summarise(Confirmed = sum(Confirmed.p)) %>% 
  arrange(Report.Date) 

# Recovered
covid19.jh.r <- covid19.jh.r %>% 
  select(-c(Province.State, Lat, Long)) %>% 
  gather(key = "Report.Date", value = "Recovered.p", -Country.Region) %>% 
  mutate(Report.Date = as.Date(str_remove(Report.Date, "X"), '%m.%d.%y'),
         Country.Region = ifelse(Country.Region=='United Kingdom','UK',Country.Region)) %>% 
  group_by(Country.Region, Report.Date) %>% 
  summarise(Recovered = sum(Recovered.p)) %>% 
  arrange(Report.Date)

# Deaths
covid19.jh.d <- covid19.jh.d %>% 
  select(-c(Province.State, Lat, Long)) %>% 
  gather(key = "Report.Date", value = "Deaths.p", -Country.Region) %>% 
  mutate(Report.Date = as.Date(str_remove(Report.Date, "X"), '%m.%d.%y'),
         Country.Region = ifelse(Country.Region=='United Kingdom','UK',Country.Region)) %>% 
  group_by(Country.Region, Report.Date) %>% 
  summarise(Deaths = sum(Deaths.p)) %>% 
  arrange(Report.Date)

# Consolidado
covid19.jh <- covid19.jh.c %>% 
  left_join(covid19.jh.r, by = c("Country.Region", "Report.Date")) %>%
  left_join(covid19.jh.d, by = c("Country.Region", "Report.Date")) %>% 
  select(Report.Date, everything()) %>% 
  group_by(Country.Region) %>% 
  mutate(Confirmed = ifelse(Country.Region=='Peru' & Report.Date=='2020-03-20',263,Confirmed),
         Confirmed = ifelse(Country.Region=='Chile' & Report.Date=='2020-03-19',342,Confirmed),
         New.Cases = Confirmed - lag(Confirmed, order_by = Report.Date),
         New.Cases = ifelse(is.na(New.Cases),0,New.Cases),
         New.Deaths = Deaths - lag(Deaths, order_by = Report.Date),
         New.Deaths = ifelse(is.na(New.Deaths),0,New.Deaths),
         Two.days.var = Confirmed / lag(Confirmed, order_by = Report.Date, n = 2) -1,
         Two.days.var = ifelse(is.na(Two.days.var),0,Two.days.var),
         Five.days.var = Confirmed / lag(Confirmed, order_by = Report.Date, n = 5) -1,
         Five.days.var = ifelse(is.na(Five.days.var),0,Five.days.var),
         Actives = Confirmed - Recovered - Deaths,
         Recov.Rate = ifelse(Confirmed==0,0,round(Recovered/Confirmed,4)),
         Death.Rate = ifelse(Confirmed==0,0,round(Deaths/Confirmed,4)))

# Last Report Date
Latest.Date <- max(covid19.jh$Report.Date)
```

```{r, echo=FALSE}
paste0("Fecha de último reporte: ", Latest.Date)
```

```{r, echo=FALSE}
# Resumen
covid19.jh %>% 
  filter(Country.Region %in% c('Peru','Ecuador','Colombia','Chile','Brazil','Bolivia') &
           Report.Date == Latest.Date) %>% 
  mutate(Death.Rate = scales::percent(Death.Rate),
         Recov.Rate = scales::percent(Recov.Rate)) %>% 
  select(Report.Date, Country.Region, Confirmed, Recovered, Recov.Rate, Deaths, Death.Rate, Actives) %>% 
  arrange(desc(Confirmed)) %>% 
  kable(align = c("crcccc")) %>% 
  kable_styling(fixed_thead = T,
                bootstrap_options = c("striped", "hover", "condensed"),
                full_width = F, position = "left")
```

```{r, echo=FALSE}
# Resumen
covid19.jh %>% 
  filter(Country.Region %in% c('Peru','Ecuador','Colombia','Chile','Brazil','Bolivia') &
           Report.Date == Latest.Date) %>% 
  mutate(Two.days.var = scales::percent(Two.days.var),
         Five.days.var = scales::percent(Five.days.var)) %>% 
  select(Report.Date, Country.Region, New.Cases, Two.days.var, Five.days.var, New.Deaths) %>% 
  arrange(desc(New.Cases)) %>% 
  kable(align = c("crcccc")) %>% 
  kable_styling(fixed_thead = T,
                bootstrap_options = c("striped", "hover", "condensed"),
                full_width = F, position = "left")
```

```{r, echo=FALSE, message=FALSE}
p <- covid19.jh %>% 
  filter(Country.Region %in% c('Peru','Ecuador','Colombia','Chile','Brazil','Bolivia') & 
           Report.Date >= '2020-03-10') %>% 
  arrange(desc(Report.Date)) %>% 
  ggplot(aes(y = Confirmed, x = Report.Date, group=Country.Region, color=Country.Region)) +
  geom_line(size=1) + 
  #geom_point(size=3, shape=21, fill="white") +
  ggtitle("Tendencia a través del tiempo del COVID-19") +
  geom_dl(aes(label = Country.Region), method = list("last.points",cex=0.8,vjust=-0.8, hjust=0.5)) +
  theme_minimal() 

p + theme(legend.position="none",
          axis.title = element_blank())
```

```{r, echo=FALSE, message=FALSE}
q <- covid19.jh %>% 
  filter(Country.Region %in% c('Peru','Ecuador','Colombia','Chile','Brazil','Bolivia') & 
           Report.Date >= '2020-03-10') %>% 
  arrange(desc(Report.Date)) %>% 
  ggplot(aes(x=Report.Date, y=New.Cases, fill=Country.Region)) + 
  geom_bar(stat="identity", position=position_dodge()) +
  geom_smooth() +
  facet_wrap(~Country.Region) +
  ggtitle("Nuevos casos confirmados de COVID-19") +
  theme_minimal()
 
q + theme(legend.position = "none",
          axis.title = element_blank(),
          axis.text.x = element_text(angle = 90, hjust = 0)) 
```

```{r, echo=FALSE, message=FALSE}
covid19.jh %>% 
  filter(Confirmed > 0 & Country.Region %in% c('Peru','Ecuador','Colombia','Chile','Brazil','Bolivia')) %>% 
  group_by(Country.Region) %>% 
  arrange(Country.Region, Report.Date) %>% 
  mutate(Dia = row_number(Country.Region)) %>% 
  select(Report.Date, Country.Region, Dia, everything()) %>% 
  ggplot(aes(y = Confirmed, x = Dia, group=Country.Region, color=Country.Region)) +
  geom_line(size=1) + 
  #geom_point(size=3, shape=21, fill="white") +
  ggtitle("Casos confirmados días después del primer contagio de COVID-19") +
  geom_dl(aes(label = Country.Region), method = list("last.points",cex=0.8,vjust=-0.8, hjust=0.5)) +
  theme_minimal() + 
  theme(legend.position="none",
          axis.title = element_blank())
```

```{r, echo=FALSE, message=FALSE}
covid19.jh %>% 
  filter(Confirmed > 0 & Country.Region %in% c('Peru','Ecuador','Colombia','Chile','Brazil','Bolivia')) %>% 
  group_by(Country.Region) %>% 
  arrange(Country.Region, Report.Date) %>% 
  mutate(Dia = row_number(Country.Region)) %>% 
  select(Report.Date, Country.Region, Dia, everything()) %>% 
  ggplot(aes(y = Deaths, x = Dia, group=Country.Region, color=Country.Region)) +
  geom_line(size=1) + 
  #geom_point(size=3, shape=21, fill="white") +
  ggtitle("Casos de mortalidad días despúes del primer contagio de COVID-19") +
  geom_dl(aes(label = Country.Region), method = list("last.points",cex=0.8,vjust=-0.8, hjust=0.5)) +
  theme_minimal() + 
  theme(legend.position="none",
          axis.title = element_blank())
```

```{r, echo=FALSE, message=FALSE}
covid19.jh %>% 
  filter(Confirmed > 0 & Country.Region %in% c('Peru','Ecuador','Colombia','Chile','Brazil','Bolivia')) %>% 
  group_by(Country.Region) %>% 
  arrange(Country.Region, Report.Date) %>% 
  mutate(Dia = row_number(Country.Region)) %>% 
  select(Report.Date, Country.Region, Dia, everything()) %>% 
  ggplot(aes(y = Death.Rate, x = Dia, group=Country.Region, color=Country.Region)) +
  geom_line(size=1) + 
  #geom_point(size=3, shape=21, fill="white") +
  ggtitle("Tasa de mortalidad días despúes del primer contagio de COVID-19") +
  geom_dl(aes(label = Country.Region), method = list("last.points",cex=0.8,vjust=-0.8, hjust=0.5)) +
  theme_minimal() + 
  theme(legend.position="none",
          axis.title = element_blank())
```

```{r, echo=FALSE, message=FALSE}
covid19.jh %>% 
  filter(Confirmed > 0 & Country.Region %in% c('Peru','Ecuador','Colombia','Chile','Brazil','Bolivia')) %>% 
  group_by(Country.Region) %>% 
  arrange(Country.Region, Report.Date) %>% 
  mutate(Dia = row_number(Country.Region)) %>% 
  select(Report.Date, Country.Region, Dia, everything()) %>% 
  ggplot(aes(y = Actives, x = Report.Date, group=Country.Region, color=Country.Region)) +
  geom_line(size=1) + 
  #geom_point(size=3, shape=21, fill="white") +
  ggtitle("Casos activos de COVID-19 (Confimados - Decesos - Recuperados)") +
  geom_dl(aes(label = Country.Region), method = list("last.points",cex=0.8,vjust=-0.8, hjust=0.5)) +
  theme_minimal() + 
  theme(legend.position="none",
          axis.title = element_blank())
```
   
   
COVID-19 En el mundo:

```{r, echo=FALSE}
# Resumen
covid19.jh %>% 
  filter(Country.Region %in% c('US','Spain','Italy','UK','France','Serbia') &
           Report.Date == Latest.Date) %>% 
  mutate(Death.Rate = scales::percent(Death.Rate),
         Recov.Rate = scales::percent(Recov.Rate)) %>% 
  select(Report.Date, Country.Region, Confirmed, Recovered, Recov.Rate, Deaths, Death.Rate, Actives) %>% 
  arrange(desc(Confirmed)) %>% 
  kable(align = c("crcccc")) %>% 
  kable_styling(fixed_thead = T,
                bootstrap_options = c("striped", "hover", "condensed"),
                full_width = F, position = "left")
```

```{r, echo=FALSE}
# Resumen
covid19.jh %>% 
  filter(Country.Region %in% c('US','Spain','Italy','UK','France','Serbia') &
           Report.Date == Latest.Date) %>% 
  mutate(Two.days.var = scales::percent(Two.days.var),
         Five.days.var = scales::percent(Five.days.var)) %>% 
  select(Report.Date, Country.Region, New.Cases, Two.days.var, Five.days.var, New.Deaths) %>% 
  arrange(desc(New.Cases)) %>% 
  kable(align = c("crcccc")) %>% 
  kable_styling(fixed_thead = T,
                bootstrap_options = c("striped", "hover", "condensed"),
                full_width = F, position = "left")
```

```{r, echo=FALSE, message=FALSE}
covid19.jh %>% 
  filter(Confirmed > 0 & Country.Region %in% c('US','Spain','Italy','UK','France','Serbia')) %>% 
  group_by(Country.Region) %>% 
  arrange(Country.Region, Report.Date) %>% 
  mutate(Dia = row_number(Country.Region)) %>% 
  select(Report.Date, Country.Region, Dia, everything()) %>% 
  ggplot(aes(y = Confirmed, x = Dia, group=Country.Region, color=Country.Region)) +
  geom_line(size=1) + 
  #geom_point(size=3, shape=21, fill="white") +
  ggtitle("Casos confirmados días después del primer contagio de COVID-19") +
  geom_dl(aes(label = Country.Region), method = list("last.points",cex=0.8,vjust=-0.8, hjust=0.5)) +
  theme_minimal() + 
  theme(legend.position="none",
          axis.title = element_blank())
```

```{r, echo=FALSE, message=FALSE}
covid19.jh %>% 
  filter(Confirmed > 0 & Country.Region %in% c('US','Spain','Italy','UK','France','Serbia')) %>% 
  group_by(Country.Region) %>% 
  arrange(Country.Region, Report.Date) %>% 
  mutate(Dia = row_number(Country.Region)) %>% 
  select(Report.Date, Country.Region, Dia, everything()) %>% 
  ggplot(aes(y = Deaths, x = Dia, group=Country.Region, color=Country.Region)) +
  geom_line(size=1) + 
  #geom_point(size=3, shape=21, fill="white") +
  ggtitle("Casos de mortalidad días después del primer contagio de COVID-19") +
  geom_dl(aes(label = Country.Region), method = list("last.points",cex=0.8,vjust=-0.8, hjust=0.5)) +
  theme_minimal() + 
  theme(legend.position="none",
          axis.title = element_blank())
```

```{r, echo=FALSE, message=FALSE}
covid19.jh %>% 
  filter(Confirmed > 0 & Country.Region %in% c('US','Spain','Italy','UK','France','Serbia')) %>% 
  group_by(Country.Region) %>% 
  arrange(Country.Region, Report.Date) %>% 
  mutate(Dia = row_number(Country.Region)) %>% 
  select(Report.Date, Country.Region, Dia, everything()) %>% 
  ggplot(aes(y = Death.Rate, x = Dia, group=Country.Region, color=Country.Region)) +
  geom_line(size=1) + 
  #geom_point(size=3, shape=21, fill="white") +
  ggtitle("Tasa de mortalidad días después del primer contagio de COVID-19") +
  geom_dl(aes(label = Country.Region), method = list("last.points",cex=0.8,vjust=-0.8, hjust=0.5)) +
  theme_minimal() + 
  theme(legend.position="none",
          axis.title = element_blank())
```

